version: '3'

services:
  db:
    build: .
    dockerfile: Dockerfile.db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    dockerfile: Dockerfile.app
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data: